---
- name: add the ssh pubkey of the zfs-autobackup user on the source machine
  ansible.posix.authorized_key:
    user: "{{ zfs_autobackup_user }}"
    key: "{{ zfs_autobackup_sshkey.public_key }}"
    comment: "{{ zfs_autobackup_user }}@{{ inventory_hostname_short }}"

- name: create the target dataset
  community.general.zfs:
    name: "{{ zfs_autobackup_target_dataset }}"
    state: present
    extra_zfs_properties:
      readonly: "on"

- name: give zfs permissions to the zfs-autobackup user
  community.general.zfs_delegate_admin:
    name: "{{ zfs_autobackup_target_dataset }}"
    users: "{{ zfs_autobackup_user }}"
    permissions: "{{ zfs_autobackup_target_permissions }}"
